### PR TITLE
Updating plugin for r10k 1.5.x

### PR DESCRIPTION
**Pull request by cdenneen**

### CODE REVIEW

**Comment by jantman** [comment]
[PullReview stats](https://www.pullreview.com/github/jantman/vagrant-r10k/reviews/pulls/pull_request_34)

**Comment by jantman** [comment]
[PullReview](https://www.pullreview.com/github/jantman/vagrant-r10k/reviews/pulls/pull_request_34?to_sha=12fceea01edd8a78b664f8dc46edbaec85e512bc) **[perfect.](https://www.pullreview.com/github/jantman/vagrant-r10k/reviews/pulls/pull_request_34)**
[Test Infection](https://www.pullreview.com/github/jantman/vagrant-r10k/reviews/pulls/pull_request_34) Your branch must be test infected.[ `lib/vagrant-r10k/action/base.rb:1`](https://www.pullreview.com/github/jantman/vagrant-r10k/reviews/pulls/pull_request_34)
[Test Infection](https://www.pullreview.com/github/jantman/vagrant-r10k/reviews/pulls/pull_request_34) Your branch must be test infected.[ `spec/unit/action_deploy_spec.rb:1`](https://www.pullreview.com/github/jantman/vagrant-r10k/reviews/pulls/pull_request_34)
[Test Infection](https://www.pullreview.com/github/jantman/vagrant-r10k/reviews/pulls/pull_request_34) Your branch must be test infected.[ `spec/unit/action_base_spec.rb:1`](https://www.pullreview.com/github/jantman/vagrant-r10k/reviews/pulls/pull_request_34)

**Comment by cdenneen** [comment]
I can't get the 2.0.x branch to pass tests but 1.5.x passed so submitted

**Comment by cdenneen** [comment]
@jantman please review the 1.5.x tests I only updated the logging ones that changed I didn't implement 1.5.x new features into tests

**Comment by jantman** [comment]
@cdenneen thanks so much for this. I'm not going to be able to look at it until this afternoon (UTC-4), but I'll do my best to get to it today.

Given the logging changes, I assume that r10k changed its internal logging from the previous debug/debug2 hack?

Also... I'm not sure if you ran the acceptance tests or not... I'll give them a whirl this afternoon and see how badly things changed...

Thanks SO MUCH for this!!!

**Comment by jantman** [comment]
It appears that a number of the acceptance tests are failing, hopefully just due to changes in output. I'm working through them now.

**Comment by jantman** [comment]
@cdenneen is there a reason you bumped the ``vagrant`` gem version from 1.7.4 to 1.8.0.dev? I'm seeing some errors I've never seen before with this gem, apparently relating to IPv6.

**Comment by cdenneen** [comment]
@jantman no i didn't intentionally do that... i removed the Gemfile.lock and ran bundle install which most likely updated the vagrant gem

**Comment by jantman** [comment]
@cdenneen thanks so much for this. I've made some fixes in https://github.com/jantman/vagrant-r10k/pull/35 to get all the tests passing. This looks good to me; I'm going to merge it and cut a release shortly.

**Pull request closed without merging**
